export interface IngredSource {
  name: string;
  type: 'git' | 'local';
  origin: string;
  cachePath: string;
  addedAt: string;
  branch?: string;
}

export interface IngredConfig {
  version: 1;
  sources: IngredSource[];
  settings: {
    targets: TargetId[];
    defaultScope: Scope;
  };
}

export interface IngredientFile {
  filePath: string;
  relativePath: string;
  sourceName: string;
  content: string;
  meta: IngredientMeta;
}

export interface IngredientMeta {
  triggers: string[];
  scope: Scope;
  priority: number;
  always: boolean;
  global: boolean;
  scopeExplicit?: boolean;
}

export type Scope = 'engineering' | 'persona';

export interface DetectedStack {
  technologies: Set<string>;
  detectedFiles: Map<string, string[]>;
  workspaceRoot: string;
}

export interface MatchResult {
  ingredient: IngredientFile;
  matchTier: 1 | 2 | 3;
  matchReason: string;
}

export interface CompiledOutput {
  personaSection: string;
  engineeringSection: string;
}

export type TargetId = 'claude' | 'cursor' | 'copilot' | 'agents' | 'gemini';

export interface Target {
  id: TargetId;
  outputPath: string;
  ensureDir?: string;
  globalOutputPath?: string;
  globalEnsureDir?: string;
  format(compiled: CompiledOutput, stack: DetectedStack): string;
  privateReference(compiledDir: string): string;
}

export interface EmitResult {
  target: TargetId;
  location: 'project' | 'global';
  status: 'written' | 'skipped';
  path?: string;
  reason?: string;
}

export interface ExternalMapping {
  files: string[];
  when: {
    dependencies?: string[];
    filesPresent?: string[];
  };
}

export interface CompileResult {
  global: CompiledOutput;
  project: CompiledOutput;
}

export const DEFAULT_META: Readonly<IngredientMeta> = Object.freeze({
  triggers: Object.freeze([]) as unknown as string[],
  scope: 'engineering' as Scope,
  priority: 0,
  always: false,
  global: false,
});

export const INGRED_SENTINEL = '<!-- Generated by ingred. Do not edit manually. Run `ingred mix` to regenerate. -->';

export interface ProjectPrivacyConfig {
  version: 1;
  privateIngredients: string[];
}

export function defaultPrivacyConfig(): ProjectPrivacyConfig {
  return { version: 1, privateIngredients: [] };
}

export function defaultConfig(): IngredConfig {
  return {
    version: 1,
    sources: [],
    settings: {
      targets: ['claude', 'cursor', 'copilot', 'agents', 'gemini'],
      defaultScope: 'engineering',
    },
  };
}
